var canny = require('canny');
window.canny = canny;
canny.add('userPool', require('../js/c-userPool')());
canny.add('userPanel', require('../js/c-userPanel')());
//canny.add('layout', require('./c-layout')());
//canny.add('lobby', require('./c-lobby')());
canny.add('panel', require('../js/c-panel')());
canny.add('rinkMessages', require('../js/c-rinkMessages')());
canny.add('rinkStats', require('../js/c-rinkStats')());
canny.add('rink', require('../js/c-rink')());